DO $$ BEGIN CREATE TYPE washer_state AS ENUM ('IDLE','RESERVED','RUNNING','MAYBE_FINISHED','FINISHED','WAITING_FOR_PICKUP'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE session_status AS ENUM ('RESERVED','RUNNING','FINISHED','PICKED_UP','CANCELLED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, nickname text NOT NULL, student_id text, user_code text NOT NULL UNIQUE, token_hash text NOT NULL UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS washers (id text PRIMARY KEY, name text NOT NULL, location text NOT NULL, state washer_state NOT NULL DEFAULT 'IDLE', current_user_id text REFERENCES users(id), reserved_at timestamptz, started_at timestamptz, finished_at timestamptz, last_activity_at timestamptz, vibration integer, current real, door_open boolean NOT NULL DEFAULT false, push_sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS laundry_sessions (id text PRIMARY KEY, washer_id text NOT NULL REFERENCES washers(id), user_id text NOT NULL REFERENCES users(id), status session_status NOT NULL, reserved_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, finished_at timestamptz, picked_up_at timestamptz, finished_notification_sent_at timestamptz, reminders_sent jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS push_subscriptions (id text PRIMARY KEY, user_id text NOT NULL REFERENCES users(id), endpoint text NOT NULL UNIQUE, p256dh text NOT NULL, auth text NOT NULL, user_agent text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS washer_events (id text PRIMARY KEY, washer_id text NOT NULL REFERENCES washers(id), type text NOT NULL, vibration integer, current real, door_open boolean, metadata jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS reminder_log (id text PRIMARY KEY, session_id text NOT NULL REFERENCES laundry_sessions(id), reminder_minutes integer NOT NULL, sent_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT reminder_session_minute_idx UNIQUE(session_id,reminder_minutes));
INSERT INTO washers (id,name,location) VALUES ('1','1번 세탁기','기숙사 세탁실'),('2','2번 세탁기','기숙사 세탁실') ON CONFLICT DO NOTHING;
