import { NextResponse } from 'next/server';
import { z } from 'zod';
import { and, asc, eq } from 'drizzle-orm';
import { getDb } from '@/lib/db';
import { sessions, washers, users } from '@/lib/db/schema';
import { processWasherEvent, reserveWasher, processPickupReminders } from '@/lib/washer/service';
import { createUser } from '@/lib/auth/identity';
import { apiError } from '@/lib/http';
function authorized(request: Request) { return !!process.env.ADMIN_PASSWORD && request.headers.get('x-admin-password') === process.env.ADMIN_PASSWORD; }
export async function GET(request: Request) { if(!authorized(request))return NextResponse.json({error:'인증이 필요합니다.'},{status:401});try{const db=getDb();const [machineList,userList,sessionList]=await Promise.all([db.select().from(washers).orderBy(asc(washers.id)),db.select({id:users.id,nickname:users.nickname,userCode:users.userCode}).from(users),db.select().from(sessions)]);const now=Date.now();const withElapsed=machineList.map(w=>({...w,elapsedMinutes:w.startedAt&&['RUNNING','MAYBE_FINISHED'].includes(w.state)?Math.max(0,Math.floor((now-w.startedAt.getTime())/60000)):null}));return NextResponse.json({washers:withElapsed,users:userList,sessions:sessionList});}catch(e){return apiError(e);} }
const schema=z.discriminatedUnion('action',[z.object({action:z.literal('reserve'),washerId:z.string(),userId:z.string()}),z.object({action:z.literal('event'),washerId:z.string(),event:z.enum(['START','ACTIVITY','NO_ACTIVITY','RESUME','FINISH','DOOR_OPEN','PICKUP','RESET'])}),z.object({action:z.literal('reminder'),washerId:z.string(),minutes:z.union([z.literal(10),z.literal(20)])}),z.object({action:z.literal('demo'),washerId:z.string(),speed:z.number().min(1).max(10)}),z.object({action:z.literal('demo-user'),nickname:z.string().trim().min(1).max(24)})]);
export async function POST(request:Request){if(!authorized(request))return NextResponse.json({error:'인증이 필요합니다.'},{status:401});try{const data=schema.parse(await request.json());if(data.action==='demo-user')return NextResponse.json({user:(await createUser(data.nickname)).user});if(data.action==='reserve')return NextResponse.json({washer:await reserveWasher(data.washerId,data.userId)});if(data.action==='event'){const sensors=data.event==='ACTIVITY'||data.event==='RESUME'?{vibration:16,current:.42,doorOpen:false}:data.event==='NO_ACTIVITY'?{vibration:0,current:0,doorOpen:false}:data.event==='DOOR_OPEN'?{doorOpen:true}:undefined;return NextResponse.json({washer:await processWasherEvent(data.washerId,data.event,sensors)});}if(data.action==='reminder'){const [session]=await getDb().select().from(sessions).where(and(eq(sessions.washerId,data.washerId),eq(sessions.status,'FINISHED')));if(!session)return NextResponse.json({error:'완료된 세탁이 없습니다.'},{status:400});await getDb().update(sessions).set({finishedAt:new Date(Date.now()-data.minutes*60_000),remindersSent:(session.remindersSent??[]).filter(m=>m!==data.minutes)}).where(eq(sessions.id,session.id));return NextResponse.json(await processPickupReminders());}return NextResponse.json({demo:true,washerId:data.washerId,speed:data.speed});}catch(e){return apiError(e);}}
